/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_pomelo_Client */

#ifndef _Included_com_netease_pomelo_Client
#define _Included_com_netease_pomelo_Client
#ifdef __cplusplus
extern "C" {
#endif
#undef com_netease_pomelo_Client_PC_RC_OK
#define com_netease_pomelo_Client_PC_RC_OK 0L
/*
 * Class:     com_netease_pomelo_Client
 * Method:    init
 * Signature: (Lcom/netease/pomelo/Client/Config;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    state
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_state
  (JNIEnv *, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    addEventHandler
 * Signature: (ILjava/lang/String;Lcom/netease/pomelo/Client/EventHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_addEventHandler
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    rmEventHandler
 * Signature: (ILjava/lang/String;Lcom/netease/pomelo/Client/EventHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_rmEventHandler
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    request
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILcom/netease/pomelo/Client/RequestCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_request
  (JNIEnv *, jobject, jstring, jstring, jint, jobject);

/*
 * Class:     com_netease_pomelo_Client
 * Method:    notify
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILcom/netease/pomelo/Client/NotifyCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_pomelo_Client_notify
  (JNIEnv *, jobject, jstring, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
